### ISSUE TITLE
Suggestion - information on how statistics are compiled

### ISSUE THREAD

**Issue by drevansa** [shaniAmare/long_read_tools#37]
Hi there, 

This is a query/ enhancement suggestion.

I'm posting here as your website email server reported an error. 

I was wondering how you calculate the statistics underpinning your graphics on the statistics tab 
https://long-read-tools.org/analysis.html

On the categories graphic (12/10/2020), "Error correction and polishing" has a count of 94 and a percentage of 20.6, and "De novo assembly" has a count of 79 and a percentage of 17.3, which equates to a total count across all categories of 457.

However, the total count is 1035 (12/10/2020).

From your table (https://long-read-tools.org/table.html), it is apparent that tools may fall into multiple categories, but what I still can't figure out is how you have derived the percentages displayed in your categories graphic.

I took a look in your Genome Biology paper (https://doi.org/10.1186/s13059-020-1935-5) but can't see this information.

Apologies if I have missed this somewhere, but it would be good to know how your stats have been compiled.

Best wishes

**Comment by shaniAmare** [comment]
Hi,

Sorry for the very very late reply. So you are right, the total, when you add up across the categories bar plots, is larger than the number of tools available on the database - and that is because, as you predicted, one tool falls into more than one category. However, the percentage is calculated only for the total number of tools and not the number of tools on the categories barplot (which would be misleading).

Does that make sense? We didn't want to include those technicalities into the review paper you mentioned above - sorry about that.

If you want the script on how the `%s` are calculated, it is available from the `plot_categories()` in [plotting.R](https://github.com/shaniAmare/long_read_tools/blob/master/R/plotting.R) 

Don't hesitate to contact me if you have further questions!

Cheers,
Shani.

**Comment by shaniAmare** [comment]
I will close this issue for now, but please feel free to re-open it if your Q is not resolved.

Cheers,
Shani.
