### ISSUE TITLE
Jasmine: SV Merging Across Samples

### ISSUE THREAD

**Issue by Nazeeefa** [shaniAmare/long_read_tools#43]
This might be relevant SV tool to add to the list :) https://github.com/mkirsche/Jasmine

**Comment by shaniAmare** [comment]
Hi @Nazeeefa,

Thanks for adding this tool - however, it does not mention on their source pages whether they tested this for long-read data. While it is presumable that this tool works with long-read data due to the input structures, it has to be validated first. So it may not be included in the database in this instance. 

Cheers
Shani. 

P.S. you can also use the [Submit page](https://long-read-tools.org/submit.html) from the database itself to provide more info on the tools you submit.
