### ISSUE TITLE
Submitted our tool, but it didn't show up

### ISSUE THREAD

**Issue by zhixingfeng** [shaniAmare/long_read_tools#55]
Hi,

I submitted our tool iGDA (https://github.com/zhixingfeng/iGDA) several months ago, but it didn't show up on the website https://long-read-tools.org. Tried it again today, but it didn't show up neither. Could you please help to add this tool. Thanks a lot.

**Comment by shaniAmare** [comment]
Hi @zhixingfeng ,

Thank you for submitting your tool, but unfortunately, that entry has not come into the database - would you mind resubmitting it again? We had some issues with our submit page in the past month which is not fixed.

Many thanks and sorry for the inconvenience caused by this.
Shani.

**Comment by anuradhawick** [comment]
Hi,

I also submitted one of my tools. Just wondering if you may have not received the submission. Tool name MetaBCC-LR. 


Thanks

**Comment by shaniAmare** [comment]
Hi @anuradhawick ,

Thanks for showing interest in the database. Unfortunately, I can't see your submission as well. Did you submit it via the submit page of the database or as a GitHub pull request? Regardless, can you please try again?

Thanks,
Shani.

**Comment by anuradhawick** [comment]
Hi Again,

I submit it via the form on the website. I will give it a try again sometime. Thanks
